### ISSUE TITLE
All log levels enabled

### ISSUE THREAD

**Issue by TheDgtl** [RetroShare/libretroshare#50]
I'm not sure whether to log this here, or in the Retroshare project, but the affected code is in libretroshare, so figured I'd start here.

The general issue is that all log calls using RsDbg(), RsInfo(), RsWarn(), RsErr(), and RsFatal() are always printed to the console, as there's nothing that toggles these methods off (They don't appear to have log level checks inside the implementation)

There are the "RS_DBG", etc macros that were added to wrap these in a variadic call style, but the "rsdebuglevel#.h" files don't actually redefine these macros, and only redefine "RS_DBG0", "RS_DBG1", etc, so currently even the variadic call style will always be printed.

**Comment by G10h4ck** [comment]
The _not numbered_ debug utility should always be printed and as wanted there is not way to silence them, the _numbered_ ones are what you are looking for, so if a debugging message is supposed to be printed at a certain debugging level but not another you use `RS_DBG#` then you choose the debugging level by including `rsdebuglevel#.h` all message having level equal or lower then the included header will be printed, the other will completely disappear at compiling time (so your binary remain as fast and little as possible).

If you found part of the code with excessive or now not always necessary debugging messages (sure you will find many), you can open PR substituting the unnumbered output with the numbered one with a reasonable debug level. Be careful to keep your PR little as when we does not accept huge PR unless it is strictly necessary (ex: when we merged IPv6 support there was no way to make the PR little or split it)
